services:
  - type: web
    name: website-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: MAX_WORKERS
        value: 3
      - key: TIMEOUT
        value: 10
    healthCheckPath: /
    autoDeploy: true
    plan: free
    disk:
      name: website-analyzer-data
      mountPath: /data
      sizeGB: 1
